#!/usr/bin/env python3
"""Run the evaluation query set against the index and render outputs/retrieval_examples.md.

  python scripts/run_test_queries.py --k 3

Two-pass by design. The first pass writes the mechanical results (chunk_id, score, preview,
metadata) plus a computed hit/miss verdict. The relevance `comment` for each query is then authored
by hand into data/eval/test_queries.json after reading real output, and the second pass renders it.
A query whose comment is still empty is reported as such rather than rendered as a placeholder.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from collections.abc import Sequence

from rag_lib import (
    REPO_ROOT,
    HybridHit,
    RetrievalError,
    SearchHit,
    Settings,
    open_collection,
    search,
)

DEFAULT_QUERIES = REPO_ROOT / "data" / "eval" / "test_queries.json"
DEFAULT_OUTPUT = REPO_ROOT / "outputs" / "retrieval_examples.md"
DEFAULT_RESULTS = REPO_ROOT / "outputs" / "retrieval_results.json"
ANALYSIS_DOC = "docs/homework2/analysis.md"

CATEGORY_BLURB = {
    "direct": "uses the corpus's own vocabulary",
    "paraphrase": "deliberately avoids the corpus's wording",
    "cross-document": "the answer spans more than one document",
    "out-of-corpus": "no document covers this — a good retriever should score low",
}


def load_queries(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        raise RetrievalError(f"{path} not found")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RetrievalError(f"{path}: invalid JSON ({exc.msg})") from exc
    queries = payload.get("queries") if isinstance(payload, dict) else None
    if not isinstance(queries, list):
        raise RetrievalError(f"{path}: expected a top-level 'queries' list")
    if len(queries) < 5:
        raise RetrievalError(f"{path}: the assignment requires at least 5 test queries")
    for position, entry in enumerate(queries):
        if (
            not isinstance(entry, dict)
            or not {"id", "category", "query"} <= entry.keys()
        ):
            raise RetrievalError(
                f"{path}: query {position} must be an object with 'id', 'category', and 'query'"
            )
    return queries


def verdict(hits: Sequence[SearchHit | HybridHit], expected: list[str]) -> str:
    # Widened for Homework #3: the improved pipeline's HybridHit carries the same metadata
    # contract, and the verdict only reads document_id — one verdict keeps the two runs comparable.
    if not hits:
        return "no results"
    top_documents = [hit.metadata.get("document_id", "") for hit in hits]
    if not expected:
        return "out-of-corpus — judged on score separation, not on document match"
    if top_documents[0] in expected:
        return "hit — top-1 is from an expected document"
    if any(document in expected for document in top_documents):
        return "partial — an expected document appears below top-1"
    return "miss — no expected document in top-k"


def score_table(records: list[dict[str, Any]]) -> list[str]:
    by_category: dict[str, list[float]] = {}
    for record in records:
        if record["hits"]:
            by_category.setdefault(record["category"], []).append(
                record["hits"][0]["score"]
            )
    lines = [
        "## Top-1 score by query category",
        "",
        "| Category | n | Mean top-1 | Range |",
        "|---|---|---|---|",
    ]
    for category, scores in by_category.items():
        mean = sum(scores) / len(scores)
        lines.append(
            f"| {category} | {len(scores)} | {mean:.3f} | {min(scores):.3f} – {max(scores):.3f} |"
        )
    lines.append("")
    return lines


def render_markdown(records: list[dict[str, Any]], *, k: int, model: str) -> str:
    lines = [
        "# Retrieval examples — Homework #2",
        "",
        f"Generated by `scripts/run_test_queries.py --k {k}`.",
        f"Embedding model: `{model}` (chunks and queries encoded with the same model).",
        "Vector store: Chroma, cosine distance. **Score = `1 - cosine_distance`**, so 1.000 is",
        "identical and 0.000 is orthogonal.",
        "",
        "The query set is deliberately mixed: direct queries that reuse the corpus's vocabulary,",
        "paraphrased queries that avoid it, cross-document queries, and one out-of-corpus query.",
        "A set of only direct queries would score uniformly high and prove nothing — see the",
        "analysis at the end.",
        "",
        "---",
        "",
    ]

    for record in records:
        category = record["category"]
        lines.append(
            f"## {record['id']} · {category} — {CATEGORY_BLURB.get(category, '')}"
        )
        lines.append("")
        lines.append(f"Query: {record['query']}")
        lines.append("")
        for hit in record["hits"]:
            lines.append(
                f"Top-{hit['rank']}: {hit['chunk_id']} | score: {hit['score']:.3f}"
            )
            lines.append(f"  Text: {hit['preview']}")
            lines.append(f"  Source: {hit['source_file']}")
            lines.append(f"  Section: {hit['section']}")
            lines.append("")
        lines.append(f"Automatic verdict: {record['verdict']}")
        lines.append(f"Comment: {record['comment']}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.extend(score_table(records))
    lines.append(
        f"Where retrieval works and where it fails: [`{ANALYSIS_DOC}`](../{ANALYSIS_DOC})"
    )
    lines.append("")
    return "\n".join(lines)


def run(
    settings: Settings,
    queries_path: Path,
    output_path: Path,
    results_path: Path,
    k: int,
) -> int:
    queries = load_queries(queries_path)
    collection = open_collection(settings)
    records: list[dict[str, Any]] = []

    for entry in queries:
        hits = search(entry["query"], settings, k=k, collection=collection)
        records.append(
            {
                "id": entry["id"],
                "category": entry["category"],
                "query": entry["query"],
                "expected_documents": entry.get("expected_documents", []),
                "verdict": verdict(hits, entry.get("expected_documents", [])),
                "comment": entry.get("comment", "").strip(),
                "hits": [
                    {
                        "rank": hit.rank,
                        "chunk_id": hit.chunk_id,
                        "score": hit.score,
                        "preview": hit.preview(),
                        "source_file": hit.metadata.get("source_file", "?"),
                        "document_id": hit.metadata.get("document_id", "?"),
                        "section": hit.metadata.get("section", "?"),
                    }
                    for hit in hits
                ],
            }
        )
        top = records[-1]["hits"][0]["score"] if records[-1]["hits"] else float("nan")
        print(f"{entry['id']}  top-1 {top:.3f}  {records[-1]['verdict']}")

    results_path.parent.mkdir(parents=True, exist_ok=True)
    results_path.write_text(
        json.dumps(
            {"model": settings.embedding_model, "k": k, "records": records}, indent=2
        )
        + "\n",
        encoding="utf-8",
    )

    missing = [record["id"] for record in records if not record["comment"]]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_markdown(records, k=k, model=settings.embedding_model), encoding="utf-8"
    )
    print(f"\nwrote {results_path}")
    print(f"wrote {output_path}")
    if missing:
        print(
            f"\nNOTE: {len(missing)} quer(y/ies) still have an empty relevance comment: "
            f"{', '.join(missing)}\n"
            f"Author them in {queries_path} from the real results above, then re-run.",
            file=sys.stderr,
        )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--queries", type=Path, default=DEFAULT_QUERIES)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    parser.add_argument("--k", type=int, default=3)
    parser.add_argument("--index-dir", type=Path, default=None)
    parser.add_argument("--collection", type=str, default=None)
    parser.add_argument("--model", type=str, default=None)
    args = parser.parse_args(argv)

    try:
        settings = Settings.from_env(
            index_dir=args.index_dir,
            collection_name=args.collection,
            embedding_model=args.model,
        )
        return run(settings, args.queries, args.output, args.results, args.k)
    except RetrievalError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
